apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::228969639977:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::228969639977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RBU2RZK5WWA9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-25T09:52:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1475"
  uid: 874f08af-c324-4083-9cc1-683c1995545f
